# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ display ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  macos1015:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: set | grep DISPLAY || echo "no DISPLAY"
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64
      - run: |
          which python
          python --version
          python tcltk.py
          
  macos-latest-python377:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: set | grep DISPLAY || echo "no DISPLAY"
      - name: Setup python
        if: ${{ true }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64
      - name: run tcltk
        #env:
        #  DISPLAY: ":0.0"
        run: |
          which python3
          python --version
          python tcltk.py 
          
  macos-latest-python3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: set | grep DISPLAY || echo "no DISPLAY"
      - name: Setup python
        if: ${{ false }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
          architecture: x64
      - name: run tcltk
        #env:
        #  DISPLAY: ":0.0"
        run: |
          which python3
          python3 --version
          python3 tcltk.py 
