# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ pkg-config ]
  pull_request:
    branches: [ pkg-config ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  selfhosted-agent_toolsdirectory:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          architecture: x64
          
      - name: Env
        run: |
          set
          
      - name: Show Python context
        run: |
          which pkg-config
          find /opt/hostedtoolcache/Python/3.8.12/x64  -name pkg-config
          #ls -l /opt/hostedtoolcache/Python/3.8.12/x64/lib/pkgconfig
          #cat /opt/hostedtoolcache/Python/3.8.12/x64/lib/pkgconfig/python3.pc
          pkg-config --debug 
          # pkg-config --list-all

