# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ pypy-output ]
  pull_request:
    branches: [ pypy-output ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-output:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Show env
        run: set
      - name: Setup python
        uses: akv-platform/setup-python@v-sedoli-v1.0.3
        with:
          python-version: pypy-3.7
          architecture: x64
      - run: |
          whoami
          ls -l /opt/hostedtoolcache
          python --version            
       
