# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  version-set:
    runs-on: macos-12
    steps:
      - name: Show env
        run: |
          set -x
          whoami
          groups
          which automationmodetool
          automationmodetool
          automationmodetool enable-automationmode-without-authentication
