
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check-output:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Show env
        run: set
      - name: python
        id: python
        uses: akv-platform/setup-python@v-sedoli-v2.0.1
        with:
          python-version: pypy-3.7
          architecture: x64
      - run: |
          whoami
          ls -l /opt/hostedtoolcache
          python --version
          echo "py ver=${{ steps.python.outputs.python-version }}"
          
