name: CI

on:
  push:

  workflow_dispatch:

jobs:
  s:
    strategy:
      matrix:
        version: [3.8, 3.9, 3.10, 3.11]
    if: ${{ true }}
    runs-on: macos-latest
    steps:
      - name: Setup python ${{ matrix.version }}
        uses: actions/setup-python@v4
      - run: |
          set -x
          which python3
          python3 --version
          python3-config --ldflags --embed
          pkg-config --libs python3-embed
  
