name: CI

on:
  push:
  workflow_dispatch:

jobs:
  version-set:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Caching Python 3.8
        uses: akv-platform/setup-python@v-sedoli-v2.0.7
        with:
          token: "XXXX"
          #${{ secrets.GH_DOTCOM_TOKEN }}
          python-version: 3.8.13
