# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ pkg-config ]
  pull_request:
    branches: [ pkg-config ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  selfhosted-agent_toolsdirectory:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.12
          architecture: x64
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip 
          python3 -m pip install --upgrade setuptools wheel
          python3 -m pip install scons flake8 scipy matplotlib DyMat pyswarm cma deap scoop pytest openpyxl distro colorama tensorflow==${{ env.TFVER }} pyDOE
          # FIXME move to pypi version of solsticepy ASAP...
          python3 -m pip install git+https://github.com/anustg/solstice-scripts.git@dev
          # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python3 -c "import DyMat; print(DyMat.__version__)"
        
      - name: Show Python context
        run: |
          echo "--------PIP LIST"
          python3 -m pip list
          echo "--------PKG-CONFIG LIST"
          pkg-config --list-all
          echo "--------DPKG LIST"
          dpkg -l "python*"
