name: CI

on:
  push:
    
  workflow_dispatch:

jobs:
  version-set:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]
        
    steps:
    
      - name: Set up Python ${{ matrix.python-version }}
          env:
            PIP_DISABLE_PIP_VERSION_CHECK: 1
            PIP_NO_PYTHON_VERSION_WARNING: 1
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          python --version
  
