# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ issue-402-tk-version ]
  pull_request:
    branches: [ issue-402-tk-version ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tk:
    # The type of runner that the job will run on
    runs-on: macos-12
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Show env
        run: set
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7
      - name: cat
        run:  |
          set
      - name: tk
        run: |
          ls -la /usr/local/opt/
          ls -la /usr/local/opt/tcl-tk/
          ls -la /usr/local/opt/tcl-tk/include
          # cat /usr/local/opt/tcl-tk/include/tk.h
          ls -la /usr/local/Cellar
          #ls -la /usr/local/Cellar/tcl-tk
          # ls -la /usr/local/Cellar/tcl-tk/include
      - name: tkinter
        run: |
          ls -la /Users/runner/hostedtoolcache/Python/3.7.13/x64
          ls -la /Users/runner/hostedtoolcache/Python/3.7.13/x64/include
          ls -la /Users/runner/hostedtoolcache/Python/3.7.13/x64/include/python3.7m
          #ls -la /Users/runner/hostedtoolcache/Python/3.7.13/x64/lib
          #ls -la /Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7
          strings /Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/lib-dynload/_tkinter.cpython-37m-darwin.so
      - name: find
        run:  |
          #brew config
          #find /Users/runner/hostedtoolcache/Python/3.7.13/ -name '*.so'
          #find /Users/runner/hostedtoolcache/Python/3.7.13/ -name '*.a'
          #find /usr/local -name '*.so'
          #find /usr/local -name '*.a'
          #rm /Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/lib-dynload/_tkinter.*.so
      - name: brew info tcl-tk
        run: |
          brew info tcl-tk
      - name: Run tk script vvvvv (closes itself after 5 seconds)
        run: |
          #export P=/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload
          #export P=/usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/lib/python3.8
          #ls -la $P
          #export LD_LIBRARY_PATH=$P/lib-dynload
          #/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/lib-dynload
          #export RUN_LD_PATH=$P/lib-dynload
          #export PYTHONHOME=$P
          #export PYTHONPATH=.:$P
          #/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/lib-dynload
          #python -c 'import os;print(os.getenv("LD_LIBRARY_PATH"))'
          #python -c 'import os;print(os.getenv("RUN_LD_PATH"))'
          #python -c 'import os;print(os.getenv("PYTHONHOME"))'
          #python -c 'import os;print(os.getenv("PYTHONPATH"))'
          # python -vvvvv tk_min.py
          python tk_min.py
          #sudo dtruss python tk_min.py
      - name: Run tk script dtruss (closes itself after 5 seconds)
        run: |
          sudo dtruss python tk_min.py
