name: CI

on:
  push:
    
  workflow_dispatch:
        
env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_PYTHON_VERSION_WARNING: 1
  
jobs:
  version-set:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 2
      PIP_NO_PYTHON_VERSION_WARNING: 2
        
    steps:
    
      - name: Set up Python ${{ matrix.python-version }}
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: 3
          PIP_NO_PYTHON_VERSION_WARNING: 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: true

      - run: |
          echo $PIP_DISABLE_PIP_VERSION_CHECK
          echo $PIP_NO_PYTHON_VERSION_WARNING
          python --version
          pip --version
          ${pythonLocation}/python -m pip install --ignore-installed pip
  
