name: CI

on:
  push:

  workflow_dispatch:

jobs:
  test-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: create big enough temp file
        run: |
          dd if=/dev/random of=/tmp/big bs=1048576 count=200

      - name: repro
        run: |
          node index.js /tmp/big 
          