name: CI

on:
  push:

  workflow_dispatch:

jobs:
  v4:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
#          python-version: '3.9'
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('poetry-demo/poetry.lock') }}


  v3:
    runs-on: latest-ubuntu
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
#          python-version: '3.9'
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('poetry-demo/poetry.lock') }}
