# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  toolcashe:
    runs-on: macos-latest
    if: ${{ true }}
    steps:
#      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
          architecture: x64
          
      - run: |
          python --version
          ls -la $( which python )
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/bin
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/include
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/share
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/lib
   
  binary:
    runs-on: macos-latest
    if: ${{ true }}
    steps:
#      - uses: actions/checkout@v2
      - run: |
          python --version
          ls -la $( which python )
          
      - name: Setup python
        run: |
          curl https://www.python.org/ftp/python/3.10.5/python-3.10.5-macos11.pkg --output python-3.10.5-macos11.pkg
          sudo installer -pkg python-3.10.5-macos11.pkg -target /
          ls -la /Library/Frameworks/Python.framework/Versions/

          ls -la /Users/runner/hostedtoolcache || echo "no hostedtoolcache"
          ls -la /Users/runner/hostedtoolcache/Python || echo "no hostedtoolcache/Python"
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5  || echo "no hostedtoolcache/Python/3.1056"
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64  || echo "no hostedtoolcache/Python/3.10.5/x64"
          sudo mkdir -p /Users/runner/hostedtoolcache/Python/3.10.5/x64
          sudo ln -s /Library/Frameworks/Python.framework/Versions/3.10/bin /Users/runner/hostedtoolcache/Python/3.10.5/x64/bin
          sudo ln -s /Library/Frameworks/Python.framework/Versions/3.10/include /Users/runner/hostedtoolcache/Python/3.10.5/x64/include
          sudo ln -s /Library/Frameworks/Python.framework/Versions/3.10/share /Users/runner/hostedtoolcache/Python/3.10.5/x64/share
          sudo ln -s /Library/Frameworks/Python.framework/Versions/3.10/lib /Users/runner/hostedtoolcache/Python/3.10.5/x64/lib
          
      - run: |
          export PATH="/Users/runner/hostedtoolcache/Python/3.10.5/x64/bin:$PATH"
          python --version
          ls -la $( which python )
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/bin
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/include
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/share
          ls -la /Users/runner/hostedtoolcache/Python/3.10.5/x64/lib
