name: CI

on:
  push:

  workflow_dispatch:

jobs:
  s:
    strategy:
      matrix:
        version: [3.8, 3.9, "3.10", 3.11]
    if: ${{ true }}
    runs-on: macos-latest
    steps:
      - name: Setup python ${{ matrix.version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          
      - run: |
          echo "import sysconfig" > t.py
          echo "getvar = sysconfig.get_config_var" >> t.py
          echo "print(getvar('Py_ENABLE_SHARED'))" >> t.py
          echo "print(getvar('LIBPL'))" >> t.py
          python3 t.py
          
      - run: |
          set -x
          which python3-config
          cat `which python3-config`
        
      - run: |
          set -x
          path=`which python3`
          echo $path
          ls -la `dirname $path`
          python3 --version
          python3-config --ldflags --embed
          pkg-config --libs python3-embed
        if: ${{ false }}
  
