name: CI

on:
  push:
    
  workflow_dispatch:
        
env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  PIP_NO_PYTHON_VERSION_WARNING: 1
  
jobs:
  version-set:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
        
        
    steps:
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: akv-platform/setup-python@investigate-env
        with:
          python-version: ${{ matrix.python-version }}

      - run: |
          #echo $PIP_DISABLE_PIP_VERSION_CHECK
          #echo $PIP_NO_PYTHON_VERSION_WARNING
          #python --version
          #pip --version
          ${pythonLocation}/python -m ensurepip
          #${pythonLocation}/python -m pip install --ignore-installed pip --disable-pip-version-check --no-warn-script-location

