# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  toolcashe:
    runs-on: macos-latest
    if: ${{ true }}
    steps:
#      - uses: actions/checkout@v2
      
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6
          architecture: x64
          
      - run: |
          which python
          python --version
          ls -la /Users/runner/hostedtoolcache/Python/3.10.6/x64/
          ls -la /Users/runner/hostedtoolcache/Python/3.10.6/x64/bin/
   
  binary:
    runs-on: macos-latest
    if: ${{ false }}
    steps:
#      - uses: actions/checkout@v2
      - run: |
          python --version
          ls -la $( which python )
          ls -la /Library/Frameworks/Python.framework/Versions/
          
      - name: Setup python
        run: |
          curl https://www.python.org/ftp/python/3.10.6/python-3.10.6-macos11.pkg --output python-3.10.6-macos11.pkg
          sudo installer -pkg python-3.10.6-macos11.pkg -target /
          ls -la $( which python )
          ls -la /Library/Frameworks/Python.framework/Versions/
          
      - run: |
          python --version
          ls -la $( which python )
          ls -la /Library/Frameworks/Python.framework/Versions/
