# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ issue-442-ctypes-repro ]
  pull_request:
    branches: [ issue-442-ctypes-repro ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ctype:
    # The type of runner that the job will run on
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          python --version

      - name: Run tests
        run: |
          python3.10 test.py

