
name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check-output:
    runs-on: ubuntu-latest

    steps:
      - name: python
        id: python
        if: {{ false }}

        uses: akv-platform/setup-python@v-sedoli-v2.0.5
        with:
          python-version: 3.7.1
          architecture: x64
          
      - name: pypy
        id: pypy
        if: always()

        uses: akv-platform/setup-python@v-sedoli-v2.0.5
        with:
          python-version: pypy-3.7
          architecture: x64
          
      - run: |
          whoami
          ls -l /opt/hostedtoolcache
          ls -l /opt/hostedtoolcache/Python
          python --version
          echo "py ver=${{ steps.python.outputs.python-version }}"
          
