# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
   
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  version:
    runs-on: macos-latest
    steps:
     
      - run: |
          which python3
          python3 --version
          
      - run: |
          brew remove python
          ls -la /usr/local/bin
    
      - run: |
          brew update
          brew upgrade || true
          which python3
          python3 --version
          
      - run: |
          brew update
          brew upgrade
