name: CI

on:
  push:

  workflow_dispatch:

jobs:
  v4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        
      - name: pythonLocation
        env:
          LOC: ${{ env.pythonLocation }}
        run: |
          echo "LOC: $LOC"
          echo "pythonLocation: $pythonLocation"

      - name: Python Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('tests/requirements.txt') }}

  v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        
      - name: pythonLocation
        env:
          LOC: ${{ env.pythonLocation }}
        run: |
          echo "LOC: $LOC"
          echo "pythonLocation: $pythonLocation"
          
      - name: Python Cache
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('tests/requirements.txt') }}
