# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ 3.9-dev-3.10 ]
  pull_request:
    branches: [ 3.9-dev-3.10 ]

  workflow_dispatch:

jobs:
  version_3_9_dev:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: set
      - name: Setup python 3.9-dev
        uses: actions/setup-python@v3
        with:
          python-version: 3.9-dev
      - run: |
          wchich python
          python --version
  version_3_9:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Show env
        run: set
      - name: Setup python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: |
          wchich python
          python --version
